name: 'PNX DS'
on: [push]
jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Fixer only needs to run on the latest stable. Fixer is also laggard
        # in supporting newer versions.
        php-versions: ['8.4']
    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
      - name: "Run PHP CS Fixer"
        run: |
          ./vendor/bin/php-cs-fixer --allow-risky=yes --dry-run fix --diff

  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.4']
    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v1"
      - name: "Run PHPStan"
        run: |
          ./vendor/bin/phpstan analyse --no-progress

